const adminProducts = [
  ['ASUS ROG Strix G16 (2025)','Gaming Laptops',134991,15,'Featured'],['Apple MacBook Pro 16" M4 Pro','Creator & Workstation',265905,8,'New arrival'],['Lenovo Legion Pro 7i Gen 9','Gaming Laptops',214891,6,'Featured'],['Dell XPS 16 (9640)','Creator & Workstation',196291,10,'New arrival'],['HP Spectre x360 16 (2025)','2-in-1 Convertibles',131591,12,'New arrival'],['Acer Predator Helios 18','Gaming Laptops',308891,4,'Featured'],['MSI Titan 18 HX','Gaming Laptops',422991,3,'Low stock'],['Samsung Galaxy Book4 Ultra','Creator & Workstation',186991,7,'New arrival'],['ASUS ROG Zephyrus G16','Gaming Laptops',186991,9,'New arrival'],['Lenovo ThinkPad X1 Carbon Gen 12','Business & Enterprise',169191,11,'New arrival'],['Dell Alienware m18 R2','Gaming Laptops',335991,5,'Featured'],['HP OMEN 17 (2025)','Gaming Laptops',176691,8,'New arrival']
];
const adminMoney = value => '₹' + value.toLocaleString('en-IN');
const views = {
  Overview: {title:'Catalog health', content: `<table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Inventory</th><th>Status</th></tr></thead><tbody>${adminProducts.slice(0,5).map(productRow).join('')}</tbody></table>`},
  Products: {title:'All products <button class="admin-cta" data-admin-action="add">+ Add product</button>', content: `<div class="admin-toolbar"><input data-admin-search type="search" placeholder="Search products"><select data-admin-filter><option value="">All categories</option><option>Gaming Laptops</option><option>Creator & Workstation</option><option>Business & Enterprise</option><option>2-in-1 Convertibles</option></select></div><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Inventory</th><th>Status</th><th>Action</th></tr></thead><tbody data-product-rows>${adminProducts.map(productRowWithAction).join('')}</tbody></table>`},
  Orders: {title:'Orders', content:'<div class="admin-empty"><b>No orders yet</b><span>Orders created through checkout will appear here with status and delivery tracking.</span></div>'},
  Customers: {title:'Customers', content:'<div class="admin-empty"><b>4 registered customers</b><span>Customer profiles, addresses, loyalty points and order history are managed through the Retech API.</span></div>'},
  Coupons: {title:'Coupons & promotions', content:'<div class="admin-list"><div><b>WELCOME10</b><span>10% off first order</span><strong>Active</strong></div><div><b>FLASH500</b><span>₹500 off orders above ₹25,000</span><strong>Active</strong></div><div><b>RETECH20</b><span>20% off selected categories</span><strong>Active</strong></div></div>'},
  Content: {title:'Content', content:'<div class="admin-list"><div><b>2 hero banners</b><span>Homepage campaigns currently live</span><strong>Live</strong></div><div><b>1 marketing popup</b><span>Active promotional message</span><strong>Live</strong></div><div><b>1 flash deal</b><span>Limited-time product promotion</span><strong>Live</strong></div></div>'}
};
function productRow(product){return `<tr><td>${product[0]}</td><td>${product[1]}</td><td>${adminMoney(product[2])}</td><td>${product[3]} units</td><td>${product[4]}</td></tr>`}
function productRowWithAction(product){return `<tr><td>${product[0]}</td><td>${product[1]}</td><td>${adminMoney(product[2])}</td><td><input class="stock-input" type="number" value="${product[3]}" min="0" data-stock-name="${product[0]}"></td><td>${product[4]}</td><td><button class="row-action" data-save-stock="${product[0]}">Save</button></td></tr>`}
const panel = document.querySelector('[data-admin-panel]');
function renderView(name){const view=views[name];document.querySelectorAll('[data-admin-tab]').forEach(button=>button.classList.toggle('active',button.dataset.adminTab===name));panel.innerHTML=`<div class="panel-heading"><h2>${view.title}</h2><span class="mode-badge">Demo mode</span></div>${view.content}`;if(name==='Products')wireProducts()}
function wireProducts(){const search=document.querySelector('[data-admin-search]'),filter=document.querySelector('[data-admin-filter]'),rows=document.querySelector('[data-product-rows]');const update=()=>{const term=search.value.toLowerCase(), category=filter.value;rows.innerHTML=adminProducts.filter(p=>(!term||p[0].toLowerCase().includes(term))&&(!category||p[1]===category)).map(productRowWithAction).join('')};search.addEventListener('input',update);filter.addEventListener('change',update)}
document.querySelectorAll('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>renderView(button.dataset.adminTab)));
document.addEventListener('click',event=>{const save=event.target.closest('[data-save-stock]');if(save){save.textContent='Saved';save.classList.add('saved');setTimeout(()=>{save.textContent='Save';save.classList.remove('saved')},1400)}const add=event.target.closest('[data-admin-action="add"]');if(add){panel.insertAdjacentHTML('beforeend','<div class="admin-form"><h3>Add product</h3><input placeholder="Product name"><input placeholder="Selling price" type="number"><button class="admin-cta" data-admin-action="close-form">Save draft</button></div>')}if(event.target.closest('[data-admin-action="close-form"]')){event.target.closest('.admin-form').remove()}});
renderView('Overview');
