const adminProducts = [
  ['ASUS ROG Strix G16 (2025)','Gaming Laptops',134991,15,'Featured'],['Apple MacBook Pro 16" M4 Pro','Creator & Workstation',265905,8,'New arrival'],['Lenovo Legion Pro 7i Gen 9','Gaming Laptops',214891,6,'Featured'],['Dell XPS 16 (9640)','Creator & Workstation',196291,10,'New arrival'],['HP Spectre x360 16 (2025)','2-in-1 Convertibles',131591,12,'New arrival'],['Acer Predator Helios 18','Gaming Laptops',308891,4,'Featured'],['MSI Titan 18 HX','Gaming Laptops',422991,3,'Low stock'],['Samsung Galaxy Book4 Ultra','Creator & Workstation',186991,7,'New arrival'],['ASUS ROG Zephyrus G16','Gaming Laptops',186991,9,'New arrival'],['Lenovo ThinkPad X1 Carbon Gen 12','Business & Enterprise',169191,11,'New arrival'],['Dell Alienware m18 R2','Gaming Laptops',335991,5,'Featured'],['HP OMEN 17 (2025)','Gaming Laptops',176691,8,'New arrival']
];
const adminMoney = value => '₹' + value.toLocaleString('en-IN');
const apiUrl = window.FLASHDEAL_API_URL || '';
const tableNames = ['users','customer_profiles','addresses','brands','categories','tags','products','product_tags','laptop_specs','product_images','product_videos','product_variants','discounts','coupons','coupon_customers','flash_deals','cart_items','orders','order_items','order_status_history','delivery_tracking','wishlists','reviews','questions_answers','price_alerts','back_in_stock_alerts','inventory_transactions','banners','audit_logs','marketing_popups'];
const views = {
  Overview: {title:'Catalog health', content: `<table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Inventory</th><th>Status</th></tr></thead><tbody>${adminProducts.slice(0,5).map(productRow).join('')}</tbody></table>`},
  Products: {title:'All products <button class="admin-cta" data-admin-action="add">+ Add product</button>', content: `<div class="admin-toolbar"><input data-admin-search type="search" placeholder="Search products"><select data-admin-filter><option value="">All categories</option><option>Gaming Laptops</option><option>Creator & Workstation</option><option>Business & Enterprise</option><option>2-in-1 Convertibles</option></select></div><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Inventory</th><th>Status</th><th>Action</th></tr></thead><tbody data-product-rows>${adminProducts.map(productRowWithAction).join('')}</tbody></table>`},
  Orders: {title:'Orders', content:'<div class="admin-empty"><b>No orders yet</b><span>Orders created through checkout will appear here with status and delivery tracking.</span></div>'},
  Customers: {title:'Customers', content:'<div class="admin-empty"><b>4 registered customers</b><span>Customer profiles, addresses, loyalty points and order history are managed through the Retech API.</span></div>'},
  Coupons: {title:'Coupons & promotions', content:'<div class="admin-list"><div><b>WELCOME10</b><span>10% off first order</span><strong>Active</strong></div><div><b>FLASH500</b><span>₹500 off orders above ₹25,000</span><strong>Active</strong></div><div><b>RETECH20</b><span>20% off selected categories</span><strong>Active</strong></div></div>'},
  Content: {title:'Content', content:'<div class="admin-list"><div><b>2 hero banners</b><span>Homepage campaigns currently live</span><strong>Live</strong></div><div><b>1 marketing popup</b><span>Active promotional message</span><strong>Live</strong></div><div><b>1 flash deal</b><span>Limited-time product promotion</span><strong>Live</strong></div></div>'}
  ,Database: {title:'Database tables', content:`<div class="admin-toolbar"><input data-admin-key type="password" placeholder="Admin API key"><button class="admin-cta" data-admin-action="load-tables">Load live tables</button></div><div class="table-grid">${tableNames.map(name=>`<button class="table-card" data-db-table="${name}"><b>${name}</b><span>View rows →</span></button>`).join('')}</div><div data-db-output></div>`}
};
function productRow(product){return `<tr><td>${product[0]}</td><td>${product[1]}</td><td>${adminMoney(product[2])}</td><td>${product[3]} units</td><td>${product[4]}</td></tr>`}
function productRowWithAction(product){return `<tr><td>${product[0]}</td><td>${product[1]}</td><td>${adminMoney(product[2])}</td><td><input class="stock-input" type="number" value="${product[3]}" min="0" data-stock-name="${product[0]}"></td><td>${product[4]}</td><td><button class="row-action" data-save-stock="${product[0]}">Save</button></td></tr>`}
const panel = document.querySelector('[data-admin-panel]');
function renderView(name){const view=views[name];document.querySelectorAll('[data-admin-tab]').forEach(button=>button.classList.toggle('active',button.dataset.adminTab===name));panel.innerHTML=`<div class="panel-heading"><h2>${view.title}</h2><span class="mode-badge">${name==='Database'&&apiUrl?'API ready':'Demo mode'}</span></div>${view.content}`;if(name==='Products')wireProducts()}
function wireProducts(){const search=document.querySelector('[data-admin-search]'),filter=document.querySelector('[data-admin-filter]'),rows=document.querySelector('[data-product-rows]');const update=()=>{const term=search.value.toLowerCase(), category=filter.value;rows.innerHTML=adminProducts.filter(p=>(!term||p[0].toLowerCase().includes(term))&&(!category||p[1]===category)).map(productRowWithAction).join('')};search.addEventListener('input',update);filter.addEventListener('change',update)}
document.querySelectorAll('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>renderView(button.dataset.adminTab)));
document.addEventListener('click',event=>{const save=event.target.closest('[data-save-stock]');if(save){save.textContent='Saved';save.classList.add('saved');setTimeout(()=>{save.textContent='Save';save.classList.remove('saved')},1400)}const add=event.target.closest('[data-admin-action="add"]');if(add){panel.insertAdjacentHTML('beforeend','<form class="admin-form" data-product-form><h3>Add product</h3><input name="name" required placeholder="Product name"><input name="sku" required placeholder="SKU"><input name="brand_id" required placeholder="Brand ID, e.g. br_asus"><input name="category_id" required placeholder="Category ID, e.g. cat_gaming"><input name="price" required placeholder="Selling price" type="number"><input name="mrp" required placeholder="MRP" type="number"><button class="admin-cta" type="submit">Create product</button></form>')}if(event.target.closest('[data-admin-action="close-form"]')){event.target.closest('.admin-form').remove()}const load=event.target.closest('[data-admin-action="load-tables"]');if(load)loadTables();const table=event.target.closest('[data-db-table]');if(table)loadTable(table.dataset.dbTable);const addRow=event.target.closest('[data-db-add]');if(addRow)loadSchemaForm(addRow.dataset.dbAdd);const saveRow=event.target.closest('[data-db-save]');if(saveRow)saveRowData(saveRow);const deleteRow=event.target.closest('[data-db-delete]');if(deleteRow)deleteRowData(deleteRow)});
async function loadSchemaForm(table){const key=document.querySelector('[data-admin-key]').value,output=document.querySelector('[data-db-output]');const response=await fetch(`${apiUrl}/admin/tables/${table}/schema`,{headers:{'x-admin-key':key}});if(!response.ok)return toastAdmin('Unauthorized or API unavailable');const schema=await response.json();output.insertAdjacentHTML('afterbegin',`<form class="admin-form" data-generic-form="${table}"><h3>Add row to ${table}</h3>${schema.filter(column=>!['id','created_at','updated_at','password_hash'].includes(column.name)).map(column=>`<label>${column.name}<input name="${column.name}" ${column.notnull?'required':''}></label>`).join('')}<button class="admin-cta" type="submit">Create row</button></form>`)}
async function saveRowData(button){const row=button.closest('[data-db-row]'),data=Object.fromEntries([...row.querySelectorAll('[data-db-field]')].map(input=>[input.dataset.dbField,input.value])),key=document.querySelector('[data-admin-key]').value;const response=await fetch(`${apiUrl}/admin/tables/${button.dataset.dbSave}/${encodeURIComponent(row.dataset.dbRow)}`,{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify(data)});toastAdmin(response.ok?'Row updated':'Update failed')}
async function deleteRowData(button){if(!confirm('Delete this row?'))return;const row=button.closest('[data-db-row]'),key=document.querySelector('[data-admin-key]').value;const response=await fetch(`${apiUrl}/admin/tables/${button.dataset.dbDelete}/${encodeURIComponent(row.dataset.dbRow)}`,{method:'DELETE',headers:{'x-admin-key':key}});if(response.ok)row.remove();toastAdmin(response.ok?'Row deleted':'Delete failed')}
async function loadTables(){const key=document.querySelector('[data-admin-key]').value;if(!apiUrl)return toastAdmin('Set the deployed API URL first');try{const response=await fetch(`${apiUrl}/admin/tables`,{headers:{'x-admin-key':key}});if(!response.ok)throw new Error('Unauthorized or API unavailable');const rows=await response.json();document.querySelectorAll('[data-db-table]').forEach(button=>{const item=rows.find(row=>row.table===button.dataset.dbTable);button.querySelector('span').textContent=`${item?.count||0} rows →`});toastAdmin('Live table counts loaded')}catch(error){toastAdmin(error.message)}}
async function loadTable(table){const key=document.querySelector('[data-admin-key]').value,output=document.querySelector('[data-db-output]');if(!apiUrl)return toastAdmin('Set the deployed API URL first');try{const headers={'x-admin-key':key};const [schemaResponse,rowsResponse]=await Promise.all([fetch(`${apiUrl}/admin/tables/${table}/schema`,{headers}),fetch(`${apiUrl}/admin/tables/${table}`,{headers})]);if(!schemaResponse.ok||!rowsResponse.ok)throw new Error('Unauthorized or API unavailable');const schema=await schemaResponse.json(),rows=await rowsResponse.json(),editable=!['users','audit_logs','orders','order_items'].includes(table);output.innerHTML=`<div class="table-output-head"><h3>${table} · ${rows.length} rows</h3>${editable?`<button class="admin-cta" data-db-add="${table}">+ Add row</button>`:''}</div><div class="row-list">${rows.map(row=>`<div class="db-row" data-db-row="${row.id||''}">${schema.map(column=>`<label>${column.name}<input data-db-field="${column.name}" value="${String(row[column.name]??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}" ${column.name==='id'||column.name==='created_at'||column.name==='updated_at'||column.name==='password_hash'||!editable?'readonly':''}></label>`).join('')}${editable&&row.id?`<div class="row-actions"><button class="row-action" data-db-save="${table}">Save changes</button><button class="row-action danger" data-db-delete="${table}">Delete</button></div>`:''}</div>`).join('')}</div>`;output.dataset.dbSchema=JSON.stringify(schema)}catch(error){toastAdmin(error.message)}}
document.addEventListener('submit',async event=>{const form=event.target.closest('[data-product-form]');if(!form)return;event.preventDefault();if(!apiUrl)return toastAdmin('Set the deployed API URL first');const body=Object.fromEntries(new FormData(form));body.price=Number(body.price);body.mrp=Number(body.mrp);try{const response=await fetch(`${apiUrl}/admin/catalog`,{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':document.querySelector('[data-admin-key]')?.value||''},body:JSON.stringify(body)});if(!response.ok)throw new Error('Product creation failed');toastAdmin('Product created in Turso');form.remove()}catch(error){toastAdmin(error.message)}});
function toastAdmin(message){let existing=document.querySelector('[data-admin-toast]');if(!existing){existing=document.body.appendChild(document.createElement('div'));existing.className='toast';existing.setAttribute('data-admin-toast','')}existing.textContent=message;existing.classList.add('show');setTimeout(()=>existing.classList.remove('show'),2200)}
renderView('Overview');
