let catalog = [
  ['prod_1','ASUS ROG Strix G16 (2025)','ASUS ROG & Zenbook','Gaming Laptops',134991,179990,15,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800'],
  ['prod_2','Apple MacBook Pro 16" M4 Pro','Apple','Creator & Workstation',265905,299900,8,'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800'],
  ['prod_3','Lenovo Legion Pro 7i Gen 9','Lenovo','Gaming Laptops',214891,269990,6,'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800'],
  ['prod_4','Dell XPS 16 (9640)','Dell Alienware & XPS','Creator & Workstation',196291,239990,10,'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800'],
  ['prod_5','HP Spectre x360 16 (2025)','HP Omen & Spectre','2-in-1 Convertibles',131591,159990,12,'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800'],
  ['prod_6','Acer Predator Helios 18','Acer Predator & Swift','Gaming Laptops',308891,379990,4,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800'],
  ['prod_7','MSI Titan 18 HX','MSI Titan & Stealth','Gaming Laptops',422991,499990,3,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800'],
  ['prod_8','Samsung Galaxy Book4 Ultra','Samsung Galaxy Book','Creator & Workstation',186991,229990,7,'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
  ['prod_9','ASUS ROG Zephyrus G16','ASUS ROG & Zenbook','Gaming Laptops',186991,229990,9,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800'],
  ['prod_10','Lenovo ThinkPad X1 Carbon Gen 12','Lenovo','Business & Enterprise',169191,199990,11,'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800'],
  ['prod_11','Dell Alienware m18 R2','Dell Alienware & XPS','Gaming Laptops',335991,399990,5,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800'],
  ['prod_12','HP OMEN 17 (2025)','HP Omen & Spectre','Gaming Laptops',176691,219990,8,'https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=800']
].map(([id,name,brand,category,price,mrp,stock,image])=>({id,name,brand,category,price,mrp,stock,image}));
const categories=[['Gaming Laptops','gaming-laptops','https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400'],['Thin & Light','thin-and-light','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'],['Business & Enterprise','business-laptops','https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400'],['Creator & Workstation','creator-laptops','https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400'],['Student & Budget','student-laptops','https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400'],['2-in-1 Convertibles','2-in-1-convertibles','https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400'],['Monitors & Displays','monitors','https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400']];
const brands=[['Apple','https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=220'],['ASUS ROG','https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=220'],['Lenovo','https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=220'],['Dell','https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=220'],['HP','https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=220'],['Acer','https://images.unsplash.com/photo-1625842268584-8f3296236761?w=220'],['MSI','https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=220'],['Samsung','https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=220']];
let cart=JSON.parse(localStorage.getItem('flashdeal-cart')||'[]'), wishlist=new Set(JSON.parse(localStorage.getItem('flashdeal-wishlist')||'[]'));
const money=n=>'₹'+n.toLocaleString('en-IN');
function productCard(p,tag='NEW ARRIVAL'){return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="product-tag">${tag}</span><button class="heart ${wishlist.has(p.id)?'active':''}" data-wish="${p.id}" aria-label="Add ${p.name} to wishlist">${wishlist.has(p.id)?'♥':'♡'}</button></div><div class="product-meta"><div class="product-brand">${p.brand}</div><h3 class="product-name">${p.name}</h3><div class="price">${money(p.price)} <span class="mrp">${money(p.mrp)}</span></div><button class="add-button" data-add="${p.id}">Add to cart <span>+</span></button></div></article>`}
function renderProducts(list,selector,tag){document.querySelector(selector).innerHTML=list.map(p=>productCard(p,tag)).join('')}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function openDrawer(title,html){document.querySelector('#drawer-title').textContent=title;document.querySelector('#drawer-content').innerHTML=html;document.querySelector('#drawer').classList.add('open');document.querySelector('#scrim').classList.add('show')}
function closeDrawer(){document.querySelector('#drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('show')}
function authView(mode='signin'){return `<div class="auth-panel"><p class="eyebrow">Your Retech account</p><h3>${mode==='signin'?'Welcome back.':'Make it yours.'}</h3><p class="auth-copy">${mode==='signin'?'Sign in to see your orders, saved addresses and personal offers.':'Create an account to save your setup and move through checkout faster.'}</p><div class="auth-tabs"><button class="${mode==='signin'?'active':''}" data-auth-tab="signin">Sign in</button><button class="${mode==='signup'?'active':''}" data-auth-tab="signup">Create account</button></div><form data-auth-form="${mode}">${mode==='signup'?'<label>Full name<input name="name" required placeholder="Your name"></label>':''}<label>Email address<input type="email" name="email" required placeholder="you@example.com"></label><label>Password<input type="password" name="password" required minlength="6" placeholder="At least 6 characters"></label>${mode==='signup'?'<label class="check-row"><input type="checkbox" required> I agree to the terms</label>':''}<button class="checkout" type="submit">${mode==='signin'?'Sign in securely':'Create my account'} <span>→</span></button></form><p class="auth-foot">Protected account access. Your details stay private.</p></div>`}
function cartView(){if(!cart.length)return '<div class="empty-state">Your cart is waiting for something brilliant.</div>';const items=cart.map(id=>catalog.find(p=>p.id===id)).filter(Boolean);const total=items.reduce((s,p)=>s+p.price,0);return items.map(p=>`<div class="drawer-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><b>${money(p.price)}</b></div><button data-remove="${p.id}" aria-label="Remove item">×</button></div>`).join('')+`<div class="drawer-total"><span>Total</span><span>${money(total)}</span></div><button class="checkout" data-action="checkout">Continue to checkout</button><div class="login-note">Sign in at checkout to save your address, unlock coupons and track every order.</div>`}
function updateCart(){localStorage.setItem('flashdeal-cart',JSON.stringify(cart));document.querySelector('#cart-count').textContent=cart.length}
function showCatalog(query=''){const found=catalog.filter(p=>(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(query.toLowerCase()));renderProducts(found,'#new-arrivals','CATALOG');document.querySelector('#new-arrivals').scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#hero').innerHTML=`<div class="hero-copy"><p class="eyebrow">New season / 2025</p><h1>Make room for <em>more.</em></h1><p>Powerful laptops, considered prices, and a little more joy in your everyday setup.</p><button class="dark-button" data-action="catalog">Shop new arrivals <span>↗</span></button></div><div class="hero-image" style="background-image:url('https://images.unsplash.com/photo-1603302576839-37fff3a6fb50?w=1200&auto=format&fit=crop&q=85')"><div class="hero-badge">UP TO<br>30% OFF<br>SELECTED</div></div>`;
document.querySelector('#categories').innerHTML=categories.map(c=>`<button class="category" data-category="${c[1]}"><img src="${c[2]}" alt=""><h3>${c[0]}</h3></button>`).join('');
document.querySelector('#brands').innerHTML=brands.map(b=>`<div class="brand-item"><img src="${b[1]}" alt="${b[0]}"><strong>${b[0]}</strong></div>`).join('');
function loadRemoteCatalog(){if(!window.FLASHDEAL_API_URL)return;fetch(`${window.FLASHDEAL_API_URL}/catalog`).then(response=>response.ok?response.json():[]).then(remote=>{if(!remote.length)return;catalog=remote.map(p=>({id:p.id,name:p.name,brand:p.brand_name,category:p.category_name,price:Number(p.selling_price),mrp:Number(p.mrp),stock:Number(p.stock_quantity),image:p.image_url||p.og_image}));renderProducts([catalog[0],catalog[1],catalog[2],catalog[3]],'#flash-deals','FLASH PRICE');renderProducts(catalog.slice(0,4),'#new-arrivals','NEW ARRIVAL');toast('Catalog synced with Retech database')}).catch(()=>{});}
renderProducts([catalog[0],catalog[8],catalog[10],catalog[11]],'#flash-deals','FLASH PRICE');renderProducts(catalog.slice(0,4),'#new-arrivals','NEW ARRIVAL');updateCart();loadRemoteCatalog();
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){if(!cart.includes(add.dataset.add)){cart.push(add.dataset.add);updateCart();toast('Added to your cart');}else toast('Already in your cart');return}const wish=e.target.closest('[data-wish]');if(wish){wishlist.has(wish.dataset.wish)?wishlist.delete(wish.dataset.wish):wishlist.add(wish.dataset.wish);localStorage.setItem('flashdeal-wishlist',JSON.stringify([...wishlist]));wish.classList.toggle('active');wish.textContent=wishlist.has(wish.dataset.wish)?'♥':'♡';toast(wishlist.has(wish.dataset.wish)?'Saved to wishlist':'Removed from wishlist');return}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(id=>id!==remove.dataset.remove);updateCart();openDrawer('Your cart',cartView());return}const authTab=e.target.closest('[data-auth-tab]');if(authTab){openDrawer('Account',authView(authTab.dataset.authTab));return}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='cart'){openDrawer('Your cart',cartView())}if(action==='wishlist'){const items=catalog.filter(p=>wishlist.has(p.id));openDrawer('Wishlist',items.length?items.map(p=>productCard(p,'SAVED')).join(''):'<div class="empty-state">Save the pieces you love here.</div>')}if(action==='orders'||action==='checkout'){openDrawer('Account',authView())}if(action==='catalog'){showCatalog();closeDrawer()}if(action==='close')closeDrawer();});
document.addEventListener('submit',e=>{const form=e.target.closest('[data-auth-form]');if(!form)return;e.preventDefault();const name=form.elements.name?.value||form.elements.email.value.split('@')[0];localStorage.setItem('retech-user',name);toast(form.dataset.auth==='signup'?'Your Retech account is ready.':'Welcome back to Retech.');closeDrawer()});
document.querySelector('#scrim').addEventListener('click',closeDrawer);document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();showCatalog(document.querySelector('#search-input').value)});document.querySelector('#categories').addEventListener('click',e=>{const btn=e.target.closest('[data-category]');if(btn){renderProducts(catalog.filter(p=>p.category.toLowerCase().includes(btn.dataset.category.split('-')[0])),'#new-arrivals','CATEGORY');document.querySelector('#new-arrivals').scrollIntoView({behavior:'smooth'})}});
let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#install-prompt').style.display='block'});document.querySelector('#install-prompt').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}});if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
